// Code generated by scripts/gen-hiscores-names.mjs. DO NOT EDIT.
// Source: osrs-json-hiscores@2.25.0 (as pinned by Anvil.Site).
//
// The official hiscores JSON endpoint returns activities and skills by DISPLAY NAME, and the ids
// are not stable across game updates — so every lookup here matches on a case-folded name, exactly
// as the Site's parseJsonStats does. These maps are the contract between the two: change one
// without the other and stat tiles stop scoring.

package hiscores

// SkillNames maps our canonical skill key to the hiscores display name.
var SkillNames = map[string]string{
	"overall":      "Overall",
	"attack":       "Attack",
	"defence":      "Defence",
	"strength":     "Strength",
	"hitpoints":    "Hitpoints",
	"ranged":       "Ranged",
	"prayer":       "Prayer",
	"magic":        "Magic",
	"cooking":      "Cooking",
	"woodcutting":  "Woodcutting",
	"fletching":    "Fletching",
	"fishing":      "Fishing",
	"firemaking":   "Firemaking",
	"crafting":     "Crafting",
	"smithing":     "Smithing",
	"mining":       "Mining",
	"herblore":     "Herblore",
	"agility":      "Agility",
	"thieving":     "Thieving",
	"slayer":       "Slayer",
	"farming":      "Farming",
	"runecraft":    "Runecraft",
	"hunter":       "Hunter",
	"construction": "Construction",
	"sailing":      "Sailing",
}

// SkillOrder is the canonical skill key order (overall first), for stable iteration.
var SkillOrder = []string{
	"overall",
	"attack",
	"defence",
	"strength",
	"hitpoints",
	"ranged",
	"prayer",
	"magic",
	"cooking",
	"woodcutting",
	"fletching",
	"fishing",
	"firemaking",
	"crafting",
	"smithing",
	"mining",
	"herblore",
	"agility",
	"thieving",
	"slayer",
	"farming",
	"runecraft",
	"hunter",
	"construction",
	"sailing",
}

// BossNames maps our canonical boss key to the hiscores activity display name.
var BossNames = map[string]string{
	"abyssalSire":                  "Abyssal Sire",
	"alchemicalHydra":              "Alchemical Hydra",
	"amoxliatl":                    "Amoxliatl",
	"araxxor":                      "Araxxor",
	"artio":                        "Artio",
	"barrows":                      "Barrows Chests",
	"brutus":                       "Brutus",
	"bryophyta":                    "Bryophyta",
	"callisto":                     "Callisto",
	"calvarion":                    "Calvar'ion",
	"cerberus":                     "Cerberus",
	"chambersOfXeric":              "Chambers of Xeric",
	"chambersOfXericChallengeMode": "Chambers of Xeric: Challenge Mode",
	"chaosElemental":               "Chaos Elemental",
	"chaosFanatic":                 "Chaos Fanatic",
	"commanderZilyana":             "Commander Zilyana",
	"corporealBeast":               "Corporeal Beast",
	"crazyArchaeologist":           "Crazy Archaeologist",
	"dagannothPrime":               "Dagannoth Prime",
	"dagannothRex":                 "Dagannoth Rex",
	"dagannothSupreme":             "Dagannoth Supreme",
	"derangedArchaeologist":        "Deranged Archaeologist",
	"doomOfMokhaiotl":              "Doom of Mokhaiotl",
	"dukeSucellus":                 "Duke Sucellus",
	"generalGraardor":              "General Graardor",
	"giantMole":                    "Giant Mole",
	"grotesqueGuardians":           "Grotesque Guardians",
	"hespori":                      "Hespori",
	"kalphiteQueen":                "Kalphite Queen",
	"kingBlackDragon":              "King Black Dragon",
	"kraken":                       "Kraken",
	"kreeArra":                     "Kree'Arra",
	"krilTsutsaroth":               "K'ril Tsutsaroth",
	"lunarChests":                  "Lunar Chests",
	"mimic":                        "Mimic",
	"nex":                          "Nex",
	"nightmare":                    "Nightmare",
	"phosanisNightmare":            "Phosani's Nightmare",
	"obor":                         "Obor",
	"phantomMuspah":                "Phantom Muspah",
	"sarachnis":                    "Sarachnis",
	"scorpia":                      "Scorpia",
	"scurrius":                     "Scurrius",
	"shellbaneGryphon":             "Shellbane Gryphon",
	"skotizo":                      "Skotizo",
	"solHeredit":                   "Sol Heredit",
	"spindel":                      "Spindel",
	"tempoross":                    "Tempoross",
	"gauntlet":                     "The Gauntlet",
	"corruptedGauntlet":            "The Corrupted Gauntlet",
	"hueycoatl":                    "The Hueycoatl",
	"leviathan":                    "The Leviathan",
	"royalTitans":                  "The Royal Titans",
	"whisperer":                    "The Whisperer",
	"theatreOfBlood":               "Theatre of Blood",
	"theatreOfBloodHardMode":       "Theatre of Blood: Hard Mode",
	"thermonuclearSmokeDevil":      "Thermonuclear Smoke Devil",
	"tombsOfAmascut":               "Tombs of Amascut",
	"tombsOfAmascutExpertMode":     "Tombs of Amascut: Expert Mode",
	"tzKalZuk":                     "TzKal-Zuk",
	"tzTokJad":                     "TzTok-Jad",
	"vardorvis":                    "Vardorvis",
	"venenatis":                    "Venenatis",
	"vetion":                       "Vet'ion",
	"vorkath":                      "Vorkath",
	"wintertodt":                   "Wintertodt",
	"yama":                         "Yama",
	"zalcano":                      "Zalcano",
	"zulrah":                       "Zulrah",
}

// BossOrder is the canonical boss key order, for stable iteration.
var BossOrder = []string{
	"abyssalSire",
	"alchemicalHydra",
	"amoxliatl",
	"araxxor",
	"artio",
	"barrows",
	"brutus",
	"bryophyta",
	"callisto",
	"calvarion",
	"cerberus",
	"chambersOfXeric",
	"chambersOfXericChallengeMode",
	"chaosElemental",
	"chaosFanatic",
	"commanderZilyana",
	"corporealBeast",
	"crazyArchaeologist",
	"dagannothPrime",
	"dagannothRex",
	"dagannothSupreme",
	"derangedArchaeologist",
	"doomOfMokhaiotl",
	"dukeSucellus",
	"generalGraardor",
	"giantMole",
	"grotesqueGuardians",
	"hespori",
	"kalphiteQueen",
	"kingBlackDragon",
	"kraken",
	"kreeArra",
	"krilTsutsaroth",
	"lunarChests",
	"mimic",
	"nex",
	"nightmare",
	"phosanisNightmare",
	"obor",
	"phantomMuspah",
	"sarachnis",
	"scorpia",
	"scurrius",
	"shellbaneGryphon",
	"skotizo",
	"solHeredit",
	"spindel",
	"tempoross",
	"gauntlet",
	"corruptedGauntlet",
	"hueycoatl",
	"leviathan",
	"royalTitans",
	"whisperer",
	"theatreOfBlood",
	"theatreOfBloodHardMode",
	"thermonuclearSmokeDevil",
	"tombsOfAmascut",
	"tombsOfAmascutExpertMode",
	"tzKalZuk",
	"tzTokJad",
	"vardorvis",
	"venenatis",
	"vetion",
	"vorkath",
	"wintertodt",
	"yama",
	"zalcano",
	"zulrah",
}

// ClueNames maps our canonical clue key to the hiscores activity display name.
var ClueNames = map[string]string{
	"all":      "Clue Scrolls (all)",
	"beginner": "Clue Scrolls (beginner)",
	"easy":     "Clue Scrolls (easy)",
	"medium":   "Clue Scrolls (medium)",
	"hard":     "Clue Scrolls (hard)",
	"elite":    "Clue Scrolls (elite)",
	"master":   "Clue Scrolls (master)",
}

// ClueOrder is the canonical clue key order, for stable iteration.
var ClueOrder = []string{
	"all",
	"beginner",
	"easy",
	"medium",
	"hard",
	"elite",
	"master",
}

// BountyHunterNames maps our canonical Bounty Hunter mode key to its display name. Note there are
// both current and "(Legacy)" ladders — the Site keeps all four, so we do too.
var BountyHunterNames = map[string]string{
	"hunterV2": "Bounty Hunter - Hunter",
	"rogueV2":  "Bounty Hunter - Rogue",
	"hunter":   "Bounty Hunter (Legacy) - Hunter",
	"rogue":    "Bounty Hunter (Legacy) - Rogue",
}

// BountyHunterOrder is the canonical Bounty Hunter mode order, for stable iteration.
var BountyHunterOrder = []string{
	"hunterV2",
	"rogueV2",
	"hunter",
	"rogue",
}

// Standalone activities the Site reads as top-level fields rather than map entries.
const (
	ActivityLeaguePoints      = "League Points"
	ActivityDeadmanPoints     = "Deadman Points"
	ActivityLastManStanding   = "LMS - Rank"
	ActivityPvpArena          = "PvP Arena - Rank"
	ActivitySoulWarsZeal      = "Soul Wars Zeal"
	ActivityRiftsClosed       = "Rifts closed"
	ActivityColosseumGlory    = "Colosseum Glory"
	ActivityCollectionsLogged = "Collections Logged"
)

// StatsPath is the official JSON endpoint's path, relative to the gamemode base URL.
const StatsPath = "index_lite.json?player="
